Datos_estudiante/config/routes.rb
Rails.application.routes.draw do
  # Otras rutas...

  root 'estudiantes#new'  # Cambia 'estudiantes#new' por el controlador y acción deseada

  resources :estudiantes
end

Datos_estudiante/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Datos_estudiante/app/models/estudiante.rb
class Estudiante < ApplicationRecord
  validates :nombres, presence: true
  validates :apellidos, presence: true
  validates :carrera, presence: true
  validates :carnet, presence: true, uniqueness: true
end

Datos_estudiante/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Datos_estudiante/app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: %i[ show edit update destroy ]

  # GET /estudiantes or /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1 or /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes or /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: "Estudiante was successfully created." }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1 or /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: "Estudiante was successfully updated." }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1 or /estudiantes/1.json
  def destroy
    @estudiante.destroy!

    respond_to do |format|
      format.html { redirect_to estudiantes_path, status: :see_other, notice: "Estudiante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.require(:estudiante).permit(:nombres, :apellidos, :carrera, :carnet)
    end
end

Datos_estudiante/app/helpers/application_helper.rb
module ApplicationHelper
end

Datos_estudiante/app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

Datos_estudiante/app/views/estudiantes/_estudiante.html.erb
<div id="<%= dom_id estudiante %>">
  <p>
    <strong>Nombres:</strong>
    <%= estudiante.nombres %>
  </p>

  <p>
    <strong>Apellidos:</strong>
    <%= estudiante.apellidos %>
  </p>

  <p>
    <strong>Carrera:</strong>
    <%= estudiante.carrera %>
  </p>

  <p>
    <strong>Carnet:</strong>
    <%= estudiante.carnet %>
  </p>

</div>

Datos_estudiante/app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante) do |form| %>
  <% if estudiante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
        <% estudiante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombres, style: "display: block" %>
    <%= form.text_field :nombres %>
  </div>

  <div>
    <%= form.label :apellidos, style: "display: block" %>
    <%= form.text_field :apellidos %>
  </div>

  <div>
    <%= form.label :carrera, style: "display: block" %>
    <%= form.text_field :carrera %>
  </div>

  <div>
    <%= form.label :carnet, style: "display: block" %>
    <%= form.text_field :carnet %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Datos_estudiante/app/views/estudiantes/edit.html.erb
<h1>Editing estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Show this estudiante", @estudiante %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

Datos_estudiante/app/views/estudiantes/index.html.erb
<h1>Estudiantes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Carrera</th>
      <th>Carnet</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombres %></td>
        <td><%= estudiante.apellidos %></td>
        <td><%= estudiante.carrera %></td>
        <td><%= estudiante.carnet %></td>
        <td><%= link_to 'Show', estudiante %></td>
        <td><%= link_to 'Edit', edit_estudiante_path(estudiante) %></td>
        <td><%= link_to 'Destroy', estudiante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Datos_estudiante/app/views/estudiantes/new.html.erb
<h1>New estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

Datos_estudiante/app/views/estudiantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @estudiante %>

<div>
  <%= link_to "Edit this estudiante", edit_estudiante_path(@estudiante) %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>

  <%= button_to "Destroy this estudiante", @estudiante, method: :delete %>
</div>

Datos_estudiante/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatosEstudiante</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>